TRUNCATE TABLE app_product_category CASCADE;
TRUNCATE TABLE app_product CASCADE;
TRUNCATE TABLE app_category CASCADE;
TRUNCATE TABLE app_user CASCADE;

ALTER SEQUENCE hibernate_sequence RESTART WITH 100;