SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE app_product_category;
TRUNCATE TABLE app_product;
TRUNCATE TABLE app_category;
TRUNCATE TABLE app_user;

SET REFERENTIAL_INTEGRITY TRUE;

ALTER SEQUENCE hibernate_sequence RESTART WITH 100;